default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: skauter_development

test:
  <<: *default
  database: skauter_test

production:
  <<: *default
  database: skauter_production
  username: skauter
  password: <%= ENV["SKAUTER_DATABASE_PASSWORD"] %>
